# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
locale                   : "en-US"
title                    : "Sarah Miller, University of Michigan"
title_separator          : "-"
subtitle                 : "University of Michigan"
name                     : "Sarah Miller"
description              : "Economist at the University of Michigan. Contains curriculum vitae and research."
url                      : "https://sm-miller.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : sm-miller/sm-miller.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     :  #"/assets/u-m_logo-hex-withoutline.png"
masthead_title           : Sarah Miller
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true # true, false (default)

# Site Author
author:
  name             : "Sarah Miller"
  avatar           : "/assets/bio-photo.jpg"
  bio              : "Associate Professor of Business Economics and Public Policy at the Stephen M. Ross School of Business"
#  location         : "351C Lorch Hall"
  email            :
  links:
    - label: "+1 (734) 647-6978"
      icon: "fas fa-fw fa-phone-square"
#      url: "tel:+17346476978"
    - label: "mille@umich.edu"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mille@umich.edu"
    - label: "CV (.pdf)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/CV_Miller.pdf"
#    - label: "Research statement (.pdf)"
#      icon: "fas fa-fw fa-file-pdf"
#      url: "/assets/research.pdf"
#    - label: "Teaching statement (.pdf)"
#      icon: "fas fa-fw fa-file-pdf"
#      url: "/assets/teaching.pdf"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=s2bBAs0AAAAJ&hl=en"
    - label: "arXiv"
      icon: "fas fa-fw fa-link"
#      url: "https://arxiv.org/search/?searchtype=author&query=Hagemann%2C+A"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/smilleralert"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square favicon-override"
      url: "https://twitter.com/smilleralert"
    - label: "mille@umich.edu"
      icon: "fas fa-fw fa-envelope-square favicon-override"
      url: "mailto:mille@umich.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Reading Files
include:
  - _pages

kramdown:
  math_engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
